apiVersion: v1
kind: Secret
metadata:
  name: dev-smtp-secrets
  namespace: plannify-dev
type: Opaque
stringData:
  SMTP_DEFAULT_SENDER: ""
  SMTP_DEFAULT_SENDER_REPLY_TO: ""
  SMTP_USERNAME: ""
  SMTP_PASSWORD: ""
  SMTP_DOMAIN: ""
