---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-secrets
  namespace: plannify-2
spec:
  encryptedData:
    DATABASE_URL: AgBY2cLWZn2/4b0bbdNCYxwHogr7QRUxTMWsdaQFARsBePD6xlThx2n2hdO2Otzb+f9KBpjtM5ufuYxsZdJ1DXIDmeUZ0A7GKlawLIMlyg1HYnPXkgSpVDbxqO4fve1iuvjEs5AzNY5iUvRz0/SNUnHQOsj0ToIJigx4JdpxNL8pEdggatke+XAG9BIuW1JbS2MKLc+V6bQOPyEkRB1WerdPIvQqb6QmS6PebK0j00H9Ps2Y/mf4AesbwCpHz2zMSTobZOtjUDOl2ol0vynzvJd+GVj6noGMiAbeQyR6L8vfoITBYitH3H0CEL9ULDz4LvV9AtKIpxAd9aKWLs3ha7iLEqq/jezEKmRfkG9XHu3rXd+fogyG26Sk+svHUvXR4OTQeXFFyCzkcwjlFoon0/DVwn1qy9R3v2KwAOPXVz2VBq/BGVMPhNL8xyMhD6cMfEpet++e9FRZper+i3m9C7CJA8Yfn1RD6qcZ600r/Xy+VZplg1E22sCzu8j1UL6TrhVmveVWItAcxM4HHYsnvit9tAckmGtBF6gAJv4EFHUZpuDMwnzcd3omRjpZRf1l3i0twGjOp2z5cGnVJzmAGTXsj6PlYCDJqJU9MFhgJ0n9eSszevalGne61cgyglLOxHW55vAlvclZTVzopOOR1mTTC0xOh+ui1mBSUlrtvwSJYvv7mMx0xjjK5rivYlM8yNvh6MKToTW3BUge2cHWw5NIjkyN/wFp8MVmTmTZcppLzyjnP2JDSwTMAxDpCGKlsVlvIQDz3vm/vcoCZKG0xDdGNqFfnL7X+oLeRL1Gh+NABUjLcP2mvlA8CKre2TUJCw==
    REDIS_URL: AgCzJszy0439jW7fpVE8EdWt6VbFMfFsFvUmJ/eAn1ZOqAt9XYyNvGGY+5oLc/nCDcke9KcpeKSYg1bxcN4t0ZrtEPeAsqtZE/0AAkpr6wDhEANSNx3Vihf/C217tC1S+2WwG0UHcQnGp3SNvl+CnWdh7P8ZT6gEkJ7HdNfGL5Dxx6IwJSFm3qRY7L2HvdmOcf8SMkyTo7lJVJor2qmyQOu9xsm/gTjy70eB+5ZwlAp73EHrcfjRdRSWETQW+L99PLWhktnM6/AwrpCxH+KakJLryeJgS0ero0IBKggoGlXOGjnD39EUqnrJ6P1w7hVNXGBWawul5gU77TmEakJG0UUm0aASKViHjq5MwhtZ7o2cYrzvnSpmAN1y+G683rH/S6051di82YfwQwJRrmhUu7Oycsa6TiTDO+YZcnHxasHbZ+cH6DS9k6bCFqqQuAGPg+4XpBR/Ibwj2lFunqxgBiyX4n8g+E94Fhk/ibwGCjFKBuw731sA26I7RzCDlrtE1Nd5yeM+ZsKTY6kCU0vwloGFYapTnNoVgX0CnL5fHFQND4l52HGi00FzhwdJUDksxQkarymt/80JcXoSRA6cpMDMWyUe+bUbZniokb83yjMl5E/ixSpH5N/TNZ5Go0nEGL3bNGV9h4n2KqDNdxQktod+w6XOrOKDPA0YmJG4q1ra6mW+/ub7gx80NZ2k49AC/cwlBU4f3HLa87yzgaCHa27Ola8h9hHr5rSYH3yPWHkqISpccpjWRR/WbQCX3MMjGroTk53LGkKRHP43yg==
  template:
    metadata:
      name: database-secrets
      namespace: plannify-2
    type: Opaque
