---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: encryption-key-secrets
  namespace: plannify-2
spec:
  encryptedData:
    AGE_PUBLIC_KEY: AgCiWGHjS5syi4HhU7oMY7Y64szizYKceUKjlr/tEYtarB8YcIGiUO8kMj6Vy+9TOb64VAijn8KZsqFNMhNxIr9p3+hrd4CKASQMqDtEMZAmfaNNwkFz1qPBhRIvT1HsQxuJDaoHkzmu4J4lZ1H3zawxJcNh6qkgbCMPc1iH2VDRsUE6Uyhliy6+K+6/i9EC/58OGnVIZeu0XzW8blZQkExiyKX6u0yD+/BwIocI6AdYltyQQVQynkWsDX4+OMHBUGA+VagGEho0GUZJWj/d4sIvTarI+tMQ1suuAUz+bwqcyC1uT0wVMAph33Rau7U2DbF8UeLba/IJJ9qUW/GBWOWF6Cl9u+2V9SDbRr+7qMPOzG/YWdPVAnduohwkibm8WG4gXcLDXNfMWGfQ0/geDliBQxD6p68nZb/TTAJTWcg2A3ypLKPCCA6dxMZikWlNhJms8kkvuiTnHoV6Ppfm42acmopAllK5notbQMyyqNJSvJzNPouFtss7k8j5e9LyPTkiuFV0cpfCtr82qPn9clKvPoORzU5YzTwFdKUCXBfTkDhUQXmS0N7t1ly9q+TVWddJec34fVecIJPz4n3YvYqLBjQ5HZfS5bQWpQ3/Js5Eg6Aufpazd35Vi5xvzt+IycSZoZqz+MnoQ1c/KxLRyFc6i0SwRpEFKbvaXvwbY64kWbVk8OR0tIKKSuIYQLL+lDBvbt5IBuEyPJ3RqLgNpfl1JX0h3RJUjX+M2133mKMwZJYF9//5x+Nptnsc5npRdpiAylQycaKElzRsQTlPwg==
  template:
    metadata:
      name: encryption-key-secrets
      namespace: plannify-2
    type: Opaque
