---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: garage-ui-secrets
  namespace: plannify-2
spec:
  encryptedData:
    ADMIN_PASSWORD: AgCxGKfKp0lNZOWt82bpGFMO8SXtPpXrBM/gZG2410c/EGPl6ftjx+ZXXXo/Zi3SfjpmNbKD6Bg7+UqofqT/MXaEhapJhVI3ACW8l0mTckz1VTYwaw1Qw/xWVx2XuDYSi6kqPTjdHnPy4Cdi7Syt1Hsw8vPU8v2GMP6Mzcq1JVSgOkCIJKrD9h5/GvR7rDJ9lKxcAn64+T0dlYKUnog8Y0JqPkg01lCadL4OwBSgWm+JGUGdJUau8f/Qh7sY9Us99ZYWLwlR0wCe3tX5wzz2B2Xi0wylRDVO9z/81UTfy9iDmF0es2yvjrnTues/gRFCSk2vorA9DXpMn2WPguVsF/a2kRd15LAou231qgsBYKQmgp85qxwHbzZ+ybKworo5YOmfkHlTEaqL3ft+TWkH0mbSM83itp8EX+VB63krGoitPSPVKhBLsv6X0+W6UUe5/4BloUBAqwROeYE3OcQhQfJeOPANAqMCHkZjOK0rCjWdSN68/8D67tFD+uwFTqxeDa/hs90QN9apJ1uA71pUg/oMgAQtVi8H7yL47VIQ9p6K6grXaBTYyQ+ZovCNVt8GnyoyIt8kyelowqHttUyyIpZsYjHQvUjsfQl72SXZsnACWwW+44pwnLs5p2lPCX2WKzDq6X5uo4fj8IE8De4zkKxugUSHiHoJB/AO/dXdLtbzeNlISRreTm+hWabdbf4/YKLw3eaQ0G9JbwUBZRpvd8m9+35LbeHq+x6QpFozt0iBEZpeQIU2mNZm
    ADMIN_TOKEN: AgAyDpblIdkdudXPZ22Rz8xivVyFdKLhwssiURhf929DjR7O1aU+xy3iyhhYipRE4I5Otxt0UjXclYF+rrJr27dRHaZe86tviVO2yX2rrKHa31g0FM5c42TYtAULixb5kvL592sstQ1kHktpeWu620F6AGvSveSg+uhy75K/VDNtu3zMdl27OvRlvzAoTafzwaGQ6CK06Qig0tH9XKMNiy/TOyQeWWHjeb1Xsfpt6A/te726maxqOzdUmc9sdXTqX8uU0vEaf3Btf6eek+lwtw0dVm+aRVTIOmo9cjsx+d4eqYltFbRssPt8iBfFxB1WVBT4KC8X06kmsoMbZ5eocDwXxm34EoAhD5o2vt29bct0faemBLL9ocFruI4fyntpaSip7rq7snkfVW13zVLTVB/NOmAzzsv4IiZfsb/pRz6Ch1RoBF/fYWLjV0P+WjiVep+TrT9Mu0i87WXTkYVf5B8JQBsxJfHmcjf7p3Oh5nz2qFskWAVhGELZO3Yiz6+taTymKZlRdZckhYYvW7G1wyX4CCupuHVERIWvqITjyPUyI7Z8v/Fn9W90ZYVT267zyy7yTiTamwPMJTf1iuUxhzTQyNclMgPpTzYIJdSKOqShVB2YyKyFWQ3o0BYcJHkR+uPs0eU3NAn10p+5znmH2TDZ6Dw4nPNkkJ4NKG72xzqoQFOeLppkuS+n7+bFLYlb3zfQ9HylqdY7I0KSVs3+pIWM/Fz2BSTeub1Mmiml4+7GODLHJlm8Zqv+OTy7k60D538eG7kLgnkjC1R/eyBECVKFcwnOeA==
  template:
    metadata:
      name: garage-ui-secrets
      namespace: plannify-2
    type: Opaque
