---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secrets
  namespace: plannify-2
spec:
  encryptedData:
    REDIS_PASSWORD: AgCNsLu72NPs/PEd/QmQiq8gMW0QQfFvWdt+vaSLhVvRtxeJd49b6zNUumSj0hD300BmWhNs/rTPeY65ZLFTU8q6Pspas1/bO3dotNiIcRLtCxUJNiD/qtB4wFA8QmRr5/lqkgqsdCsXc/EUMbWvyINMcnBq+WFfYx5sX4BJT3XG+rLmFMD5YEwYw7aSdh5bMvls1VAU546qMixvE7+xj+dz2w5jNyWZ1bfMrPW1jpe3zxTlgxW67zuI4ELVx1bDdxUJCgz8og1UUnKVw+oDKWJB3+JXtcoCYumuVM1rGp9RsE0pDkFZ7LrzqsA93UKYUXJkZdBIV6vli7Pl1S8pPQ8IwZTe+f8A7IeYgTxuhulo3GExVkJg3jKPM9smKazB+l4rfZ2skUH5cRPsJvD+XlzNuGbGQCf40soP1zSAqecz2fbuLRDB4+yXQxQEzHz11hn72Ps+aHDrCq6zCiPnYrbx4WR1yDwFwii+TFLacdVWw3YNSYK+EfymUETRv2pxZvfLi0FVXIIUf2ivtxBvYVY7a70YMjM2Ap94lGe2dd9VmjCK1R5zaSOMM9xznKmySnFQQUHtohWdw69QbPsFSLiAfsBAsPgThE8/8MrLp9LHy7c9A19Uenu9+not7hj1C6KibG3BQMGnQGgTk0hm472UcTKnjRSE+SJCTj1XbcNicjBLEHCH5wKrBtV9EGiPffdcmHeak4NeGHw3c1kVq8rM2jeH2DtovT9kfefO6LF8e4CXZtp14VAw
  template:
    metadata:
      name: redis-secrets
      namespace: plannify-2
    type: Opaque
