---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secrets
  namespace: plannify-2
spec:
  encryptedData:
    REDIS_PASSWORD: AgA3kPpucB1I6rWKPZvNykCMWS11nO6sL1eEx6B46TfDwBIlfTvm6TQbXuJtel3jbLZG4LCAOilload/3SK0F1oXJ0cJwazV6ZvBkM65va6/jkrmtt+aCHOTMXBX0moNnspAgnJ72oFNolP9VU5H/+MqIiNT44RvGjUOYALpG/jLNEX3UOmQPn5NQPuf2gjmSPHzCiSvfIvMn8OfSEYxuuhhsZ/K8d88K2rkGPI6PwNzk4EkqIhj6ILfYoO+cywmDDQr6e1YumPxzgaF1Uu92G7GmjncyRYggPyjV3dm/LFUj4q8ULjfXTVuF9VS+k1mqkWRPWPPhWQ72tsbrLqjC3KiSTT+yuCe/96I9TPzVOeXPQd3/1eTwGTZhududqblKXw8omHdmaKS+j6wDNIQyywN9YqHTwHC8TxGk3/sjluXLDJRDGcYk0SxyeqNRf/VeRbmpcXnyMw0vOsXiisSmdw43nnx6jPw2zcVFaL4d0/Uv5FyMa02Y3YgxLfnGhQ2bZJPKH3ghQD2kwRtHI444oX5gsET1Y5xiZu4V4O8OTOqFFNB7zVjP6pNqPIneuISxT/nbPUdy0a7yZUg4ttxGgho6Gldg38DhehvBDLZZzpWUYQ7/yIGevbjK1Zj4kMgGxLMa/A6E5GGI0FBx6fSns/8eCVc822IskAN876PkzG3X6+9vnhxqd03kgW0OY1pX5V+e+UPWof7CHE26/VbvT+SlmgyNKwMSaLzPQhzKIZ7QxnIcJG7EEWo
  template:
    metadata:
      name: redis-secrets
      namespace: plannify-2
    type: Opaque
