---
# Source: redis/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: plannify-prod-redis
  namespace: plannify
  labels:
    app.kubernetes.io/instance: plannify-prod-redis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: plannify-prod-redis
    app.kubernetes.io/version: 8.8.0
    helm.sh/chart: redis-0.30.6
type: Opaque
data:
  redis-password: "NkszUWI1MGFLMzBYUlBzdA=="
  host: "cGxhbm5pZnktcHJvZC1yZWRpcy5wbGFubmlmeS5zdmM="
  port: "NjM3OQ=="
  username: "ZGVmYXVsdA=="
  uri: "cmVkaXM6Ly9kZWZhdWx0OjZLM1FiNTBhSzMwWFJQc3RAcGxhbm5pZnktcHJvZC1yZWRpcy5wbGFubmlmeS5zdmM6NjM3OQ=="
---
# Source: redis/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: plannify-prod-redis-config
  namespace: plannify
  labels:
    app.kubernetes.io/instance: plannify-prod-redis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: plannify-prod-redis
    app.kubernetes.io/version: 8.8.0
    helm.sh/chart: redis-0.30.6
data:
  redis.conf: |
    # Redis configuration
    bind * -::*
    
    # Standard Port Configuration
    port 6379
    save ""
---
# Source: redis/templates/headless-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: plannify-prod-redis-headless
  namespace: plannify
  labels:
    app.kubernetes.io/instance: plannify-prod-redis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: plannify-prod-redis
    app.kubernetes.io/version: 8.8.0
    helm.sh/chart: redis-0.30.6
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: tcp-redis
  selector:
    app.kubernetes.io/instance: plannify-prod-redis
    app.kubernetes.io/name: plannify-prod-redis
---
# Source: redis/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: plannify-prod-redis
  namespace: plannify
  labels:
    app.kubernetes.io/instance: plannify-prod-redis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: plannify-prod-redis
    app.kubernetes.io/version: 8.8.0
    helm.sh/chart: redis-0.30.6
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: tcp-redis
  selector:
    app.kubernetes.io/instance: plannify-prod-redis
    app.kubernetes.io/name: plannify-prod-redis
---
# Source: redis/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plannify-prod-redis
  namespace: plannify
  labels:
    app.kubernetes.io/instance: plannify-prod-redis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: plannify-prod-redis
    app.kubernetes.io/version: 8.8.0
    helm.sh/chart: redis-0.30.6
spec:
  serviceName: plannify-prod-redis-headless
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: plannify-prod-redis
      app.kubernetes.io/name: plannify-prod-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: plannify-prod-redis
        app.kubernetes.io/name: plannify-prod-redis
      annotations:
        checksum/config: 294a093cafef93d0e0b2d399b0d11a262d7f8618f7bfb84afaec0e75430a3dee
    spec:
      securityContext: 
        fsGroup: 999
      automountServiceAccountToken: false
      serviceAccountName: default
      containers:
        - name: redis
          securityContext: 
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 999
            runAsNonRoot: true
            runAsUser: 999
            seccompProfile:
              type: RuntimeDefault
          image: "docker.io/redis:8.8.0@sha256:aa049e689e141a4358ad1d4562dc49c88a89fbab711fd8fcc33f684c80b26301"
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - |
              CONFIG_FILE="/usr/local/etc/redis/redis.conf"

              redis-server "$CONFIG_FILE" --requirepass "${REDIS_PASSWORD}"
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: plannify-prod-redis
                  key: redis-password
            - name: REDISCLI_AUTH
              valueFrom:
                secretKeyRef:
                  name: plannify-prod-redis
                  key: redis-password
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  
                  redis-cli -h "127.0.0.1" ping
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  
                  redis-cli -h "127.0.0.1" ping 
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 128Mi
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /usr/local/etc/redis
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: plannify-prod-redis-config
      terminationGracePeriodSeconds: 30
