apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: plannify-dev-project
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/plannify-truck-driver/infrastructure.git
  destinations:
    - namespace: plannify-dev
      server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plannify-applications-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/plannify-truck-driver/infrastructure.git
    targetRevision: main
    path: argocd-applications/apps/dev
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
