---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDU16T/jsPmySRsGaJFglXwE7xkxlWEIu9EEiUwWs4XoxzjZ6dbx6uQ4wlnvwN1rYySO8aBnibRcQxdK9aZ3/tE41GQoTUT+A//NpSch96JHZs/6rHqh8RJj+/cFNHg2WiHxMTSnqary5jZnDtkRSKZWw+CR5qwxAbZkVUBkEEeUpdUpRk/SV7FA6ccjrVvtTxyuxs8QIf3WCf11HeOb7lLJzQQ/cZcMtp3Pc03+yU0WALh6Jz1OuQHTeVAw6z6IZJQYHxuQipdxWzCxyUSNwn8G279gasGDNpvsHYYkAIHhbHz0WHb+CxcSC52g5C5XgmMu6KAYmwKJDp+6/nRO1JP5u27woXeKL7sDgIzBRbvnf1qBK48FqLUjiwoe5AnhqCAqL+UYIOX4hA7mutdof4WDnslbug0HJ56bPAJ+Dp5O4dPQCtW0y2jtCs1l0iqQRIkBHjpENVeH4DpzcwbkDoz+fODggmYaEXz0b9tDHmausVMfq50tdCDZ6Q69lT3JOyfZ49Dy/y+HYDKJX+7Qwv4j9KTHQIBIBKOllzMHYDWtokQq4KksJZkOgfO3CnyLe7+sWnumNsFaWY/gao5eVYgIXDxWZDgmS5BW++uwIvDP9j9oI7hSQTogYuduXbK+IMj1cW3/BrrTeb0g9LbQyCQBDFBtAR3sG4QUfgfmlNngvNT9BOaHKqESn41Wmk5B7h8MRc4uAcvdJfyAIckfylmmlJ5m//wDVmi9avo3N4jF8M5HE+E8PMm
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
