apiVersion: v1
kind: Service
metadata:
  name: pdf-service
  namespace: plannify-2
spec:
  type: ClusterIP
  selector:
    app: pdf-service
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: grpc
