apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plannify-prod-driver-front
  namespace: argocd
spec:
  project: plannify-prod-project
  source:
    repoURL: https://github.com/plannify-truck-driver/infrastructure.git
    targetRevision: main
    path: yaml-applications/prod/driver-front
  destination:
    server: https://kubernetes.default.svc
    namespace: plannify-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
