---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAnC+thTOlgYvweXaNATDvsVi8pp3bBj6zGhaEgjTht3HWVFgbHkMGkJhD16/Y8JU+//FMZ3u8qXm5mIZTJWotocyqbDscTz6/uBsnM0L0O7X1PA+oPOQplAmjg/QTXWsSP8yI5Lic21arfGGDujPUupxWSWHFN8wbJfRzuFb5lW/UzdbpI6r+7nKntZQSUFfHzh1U6iIc4WKS4FbK6Z9ogzGdXmZqkqjzOJwQBb84SDYu92zj/wOlDOo4Rig37pWD9SVO3rd4ZBuGtU9QyBOgIgJOdlQ1GqGwoaOwGIV1rYomE0om+W0adpif4OAnbcoeJkp13Iq6xHn9moV3/kk67VAKkMI/u442a4rgoNJzQuJi1rQ7F7K0lSoWdRWODZSCjQvsVl7gROZL0nKZG56E7aIDjkXBgdopON+s2YEqtHtGoVGS5Cy/Gybsb1wVXUsA8WQ7JxOqQHjkvkT3HTwxpYxrO8baBCypIGk7iO/6PF6PJyT0sr/tV96097mu7+FU5l8P5Vj/NM0wQcnpAbhAZPBhs4qCicA6Lp3jH8Fdq0hsg1FLO7lMDdUNeyyShslIRNAJsNUml705PlISqFgBw/EITGAIl1XgUdo0SZlYoAmmVtzWNqeapIgR2LJd4qW8376kRLMl5u1s4VoMnik44sWGAwJ3l7AKtuciSuRxLls72V50WC4qtISKO0teZi8l8z8YNW831yHVcjAPH2CKWnXC0wJz2Cw5+wqVr3AsUE4gfLndjOW38
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
