---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plannify-dev-garage-ui
  namespace: plannify-dev
spec:
  encryptedData:
    ADMIN_PASSWORD: AgC6PtoDLF0PgF7a82Id1xboZa6bIgZRfVoQ7YereiQqGk+Hs17dW+YFN6d0e0ASf72+tRIhQfDY0B8Fnq2ebPl6OgvXO/Yw0S/LZSIakzqw02M5m66YktDNh1nBX16W3NqeigHbt26miBEkuRg8EqJ1gDMmwOqpH+zOAaED/zT8rxFgVGhsq9jdFJtMri9xtG7mvcrYyt4+Cm2ON+r6DYpR5TIr7LmxgmIepssqTVKrq1OCeeesvMVgvx33ThFcBp8mzUXZq7FTbpHwvgZQGXqSpXwiDZOqKPGsbErdLF9AbnoBwaKEJ21AgFW53pdNdWru7344hhkxdNaIKUaAjCDsPacAPwSgdyg74CXSeAMAu1juCBLD3M1cCO5sm62t81TuTvD21DfmgsRZgPx4piL+7hte7n3RcvhxEXesAlFKkJNV2zZOrB7go4gqayuB1cH6yy3ZxnOww2IbWxR061dnhb15+DYwHchQbwOqyzAM+0nZNdUaNZp/9c23IElW6/h/2jg/5a0aBC1IXuxQYLA6aEtNfKb3Sjw33p6kVE2nwbU1fL5mNoknFzV8omh0WmTq6wxTWfSzd10EzZHMGUIbZ1p6LYCFoSG1qcOZSLoCz0If4rBO+1hqVvJEdxgK7for9Y5fQwEp7YCQM9Y/jlNo5d29uXZo4PTk2ZoLNhdz/X/Qg+nNxzw7Oss5VdhM7IMU03nnpqBCdzYEj9iNg6SCYSNxviaCwmRQ4ZlbZ/WSEtYzRt+A54a/
    ADMIN_TOKEN: AgBH57VEIkGQKdcDwFqvQCugL6vNrP7CCRcF8wi8MRxuD3mUhl8qlfEk9tSTs5hNV62tO0Dr8tf9UBAbvHOzUMcvdGI3sSatciy0+kGQRUyHl51peymuWpeDYSujxMZOigggM7ygWnlyUUtfZ9skANFDnd797oCr+82SkRkj5VebqC+ivw4BtuA3Xqqss+dAHiIyhJku3m/wrK7YUQfXZmoEfHTp1QYI+5U0KqUQYTC/nW35EpC1+/Sc6PODQm/ABUZR+opJi+ugjJq3tEJ+C/ESERC6Sx1H+ldGgpbxc8/DYryy23/g/+ebESKjklL6Rz2mtiCMKYc+Pej7dKLdJGCqXvIRUK88BbOhfLcMbcJ7xaXZ6GJyGcC7ECnQyVIc3V1GBvDshI9A3sCIDP4RYBKzBjwiq9T7/nL/0CYO1ZMvOkhLeYJCdkvnYnCmeOAymM9DP4PVNe0BtvSkS3onBSw8ZxmWbjHLEyzBcg3cHyPN8zyFaK3CQUKsH8groOSMd+Y+rSbKzT6uv52RRtMTXFgWpdgulcxUz38KAwL1i2t1uRtrsrWfYOYtKgWotdWXCdkdKw4CJXQYKf0hqzagS4h5iUUAS+NWiEJa6afk30SGOtb1iVlAJUak/oSaYKMzDprFM6LX+N8w31AxqJzJxTTaF1XwMnrBKb68vJO+EfulCf3ds38yrzcxr7EIAp+uV9sLt2q7qKbH/yr+ewdk6WzeFumq8ZJe65HQ0pfUtOn2AFn7jrwbs08eo92ibqZPGJ9z3x1+rR1s9aAkixqM4pyAUtiiLg==
  template:
    metadata:
      name: plannify-dev-garage-ui
      namespace: plannify-dev
    type: Opaque
