---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plannify-dev-garage-ui
  namespace: plannify-dev
spec:
  encryptedData:
    ADMIN_PASSWORD: AgBZWhalPuHexgUQDBCox24zBHe8nyEdGI0iJ9HgeI1Tr+EBPiTG3QkFCgHDG2dfUWkLg/wC6kHIGJ2vqoo8xt7YXQcb9Gz4cajryP7fc8HDY2Mvg7ap8rkton+LUfNqta68P8WAGyiaC+5wauy3A93BcskTWXcfeS4ptm2E3YnOKLCe7Hx7ZOADSriEGTZjcOrqFz0AUG9GtF/aaEgTN2n0LzIJigoQ1pZms5667SvMBKaQ5RS31BYtIszUICPxSFPcdee9hpP8G+glYaDCpF7UpkapsenMY5x5JXrCtdvPPtPU1/byjPKRRwApPbiIO6qE8M8SqoHNKmErYTYP5w1wVniddreR6gDfQYVjRkmtyqtAvKPyXPxVOB3DNPphbSwK0ojPvdywmi1ee+d1zsUVzRLNDAS4hY8qfAeH9ZobaQKoF5kXlSDAVtREtkauIfT6Lu5JD9B8NVu3QLJhVFLjQlwRFWFBpSGHIyBMwMXAQS9rzE495WYJ7VTjTX2hZLpitKe9vI7CquKlGLFk/Bww0oASo+WkjXaJtXPf5/iEFYDsycM4HzqQbUgJX4hw8+XtCwLRnc0Sj9Ha0K0vuXfRgCYrox5Fq/yaNe+A5zR+fH/9y7mhZfxBg3xEasLhyQxyuX7QEXYhYzWgTCa2vDle7ojTYcNoMpImbtXeZABRnn39acxvqZQsc0HS8vw9sbI50CqmCvGHzxBz7j+yrxwEE4lVu+GkemsGo4ys9Zp3wFBs20ecYA4S
    ADMIN_TOKEN: AgBOGOCyrB3+K8Cose9BdNBTRIplo195QLlc5byngv/nvK9RJkBfnzhb6Ws5XoyEclpVDdJ/sSZDobZIu2wOHE+B8La/ASixJ2MgEPDdzn5r3SSjpffF0BhDm0wZ55wrM5er6mZkduK9UV8x0IJlldKyIOGK/bIDHWQ/F7dMf+T3JF+dWvc15BE4EhwlyR4M9Dekrvchu0aX4XbN12+M8p4ORUB/4OY8WZ8bZn8mTo90ntP7IYiFIXE1eegkTW97OgbOOSZEAoT63kFFUIeeVcuc6RwprTWagFuxB5WSitcGh8yeXxO38cDAbYFaDK0fedVsQR4PI2Mvi70f44GMt0KWo74qyXbvOjT3E10TrCQ9fEN2Vnqe+PJDJWHBNbmlrJNMhQDNA6Bj0dgPhsVHRMbPo2a1PoTBjf7SqwC8m0QgiVazu/R05FfJkqKfX8VbUtWjXOdjZnHnGR4Wusj5yZNccnrLoNWwQsLbIjluCuE2gRq5A9GfpdUNezk/ljDRIbpHhEG0Cq/5BpUi4Qff1oX3Wa661H3BShuSFHFDDjpaVn6KFJ5H+3JECcMm69Ols164IuF4uDdFT44Tt8mjekhNUppd+45Kh8g42dR519KZwRnd0tc3fj5S1KzzU78wkF7qAQwEUOzTTo2+yMg/Bm5mUYZ5yr6XNPWGxHQR91rnYjRUCDR4voA2aPfVbLAK0lUHOrh8M5fbj9Mbeg6nv2PrhsNCL9T8kkrDGkLXOSS/xkgvsiUap+K5EQfsuS2ZrjLK9uN8PSIgm3famru3ayqBjTsiRQ==
  template:
    metadata:
      name: plannify-dev-garage-ui
      namespace: plannify-dev
    type: Opaque
