apiVersion: v1
kind: Pod
metadata:
  name: dev-database-migrations
  namespace: plannify-dev
spec:
  containers:
    - name: dev-database-migrations
      image: ghcr.io/plannify-truck-driver/common-services:0.1.0
      imagePullPolicy: Always
      resources:
        requests:
          cpu: "20m"
          memory: "32Mi"
        limits:
          cpu: "20m"
          memory: "32Mi"
      env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: dev-database-secrets
              key: DATABASE_URL
  restartPolicy: Never
