apiVersion: v1
kind: Secret
metadata:
  name: s3-secrets
  namespace: plannify-2
type: Opaque
stringData:
  S3_ACCESS_KEY: "plannify_access_key"
  S3_SECRET_KEY: "plannify_secret_key"
  S3_BUCKET_NAME: "plannify-bucket"
  S3_ENDPOINT: "https://s3.plannify.be"
  S3_REGION: "eu-west-1"
